services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=glacial_db'
      - 'POSTGRES_USER=dev'
      - 'POSTGRES_PASSWORD=321123'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
